version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule: { interval: "weekly" }
    open-pull-requests-limit: 5
    groups:
      security-patches:
        patterns: ["*"]
        update-types: ["security"]

  - package-ecosystem: "npm"
    directory: "/frontend/panel"
    schedule: { interval: "weekly" }
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: { interval: "weekly" }
