version: '3.9'

services:
  # ============================================
  # Redis — Distributed Rate Limiting
  # ============================================
  redis:
    image: redis:7-alpine
    container_name: levibot-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - levibot

  # ============================================
  # API — FastAPI Backend
  # ============================================
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: levibot-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    environment:
      - REDIS_URL=redis://redis:6379/0
      - PYTHONUNBUFFERED=1
      - BUILD_VERSION=${BUILD_VERSION:-1.5.0-dev}
      - BUILD_SHA=${BUILD_SHA:-local}
      - BUILD_BRANCH=${BUILD_BRANCH:-main}
    volumes:
      - ./backend/data:/app/backend/data
      - ./configs:/app/configs
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/healthz" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - levibot

  # ============================================
  # Panel — React Frontend (Nginx)
  # ============================================
  panel:
    build:
      context: .
      dockerfile: Dockerfile.panel
    container_name: levibot-panel
    restart: unless-stopped
    ports:
      - "3001:80"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - api
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - levibot

networks:
  levibot:
    driver: bridge

volumes:
  redis_data:
    driver: local
