groups:
  - name: levibot_ml_health
    interval: 30s
    rules:
      # =====================================================
      # Data Health Alerts
      # =====================================================

      - alert: DataStale60s
        expr: levibot_features_staleness_seconds > 60
        for: 3m
        labels:
          severity: warning
          component: data
        annotations:
          summary: "Market data stale for {{ $labels.symbol }}"
          description: "No fresh data for {{ $value }}s. Check MEXC WS feed."
          runbook: "https://github.com/levibot/docs/blob/main/TROUBLESHOOTING.md#data-stale"

      - alert: TicksDropped
        expr: levibot_market_ticks_per_minute < 30
        for: 3m
        labels:
          severity: warning
          component: data
        annotations:
          summary: "Market tick rate dropped for {{ $labels.symbol }}"
          description: "Only {{ $value }} ticks/min (expected >100)"

      # =====================================================
      # Model Performance Alerts
      # =====================================================

      - alert: ModelLatencyP95High
        expr: histogram_quantile(0.95, rate(levibot_model_latency_seconds_bucket[5m])) > 0.3
        for: 5m
        labels:
          severity: warning
          component: model
        annotations:
          summary: "High ML prediction latency (p95 > 300ms)"
          description: "Model {{ $labels.model_name }} p95 latency: {{ $value }}s"

      - alert: PredictErrorSpike
        expr: rate(levibot_model_errors_total[5m]) > 0.01
        for: 5m
        labels:
          severity: critical
          component: model
        annotations:
          summary: "Prediction error rate > 1%"
          description: "Model {{ $labels.model_name }}: {{ $value }} errors/s"

      - alert: FallbackRateHigh
        expr: rate(levibot_fallback_events_total[10m]) / rate(levibot_predict_requests_total[10m]) > 0.1
        for: 5m
        labels:
          severity: warning
          component: model
        annotations:
          summary: "High fallback rate (>10%)"
          description: "{{ $value | humanizePercentage }} of predictions falling back. Reason: {{ $labels.reason }}"

      # =====================================================
      # System Health
      # =====================================================

      - alert: DBPoolExhausted
        expr: levibot_db_pool_connections{state="idle"} == 0
        for: 2m
        labels:
          severity: critical
          component: database
        annotations:
          summary: "Database connection pool exhausted"
          description: "No idle connections available. Consider increasing pool size."

      # =====================================================
      # Recording Rules (for dashboards)
      # =====================================================

      - record: levibot:predict_latency:p50
        expr: histogram_quantile(0.50, rate(levibot_model_latency_seconds_bucket[5m]))

      - record: levibot:predict_latency:p95
        expr: histogram_quantile(0.95, rate(levibot_model_latency_seconds_bucket[5m]))

      - record: levibot:predict_latency:p99
        expr: histogram_quantile(0.99, rate(levibot_model_latency_seconds_bucket[5m]))

      - record: levibot:predict_success_rate
        expr: |
          sum(rate(levibot_predict_requests_total{status="success"}[5m]))
          /
          sum(rate(levibot_predict_requests_total[5m]))

      - record: levibot:fallback_rate
        expr: |
          sum(rate(levibot_fallback_events_total[5m]))
          /
          sum(rate(levibot_predict_requests_total[5m]))
