global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'levibot-prod'
    environment: 'production'

# Alertmanager configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093

# Load rules
rule_files:
  - '/etc/prometheus/alerts.yml'

# Scrape configurations
scrape_configs:
  # LeviBot API
  - job_name: 'levibot-api'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['api:8000']
        labels:
          service: 'api'
          component: 'backend'

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'
          component: 'monitoring'

  # Node exporter (if added)
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100']
  #       labels:
  #         service: 'node-exporter'
  #         component: 'system'

  # Caddy metrics (if enabled)
  # - job_name: 'caddy'
  #   static_configs:
  #     - targets: ['proxy:2019']
  #       labels:
  #         service: 'caddy'
  #         component: 'proxy'
