name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is your feature request related to a problem?
      placeholder: "Example: I'm frustrated when I have to manually check signal confidence scores..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: |
        Example: Add a `/signals/batch` endpoint that accepts multiple signals and returns scores in parallel.
        
        API design:
        ```json
        POST /signals/batch
        {
          "signals": [
            {"text": "BUY BTC @ 60000", "source": "telegram"},
            {"text": "SELL ETH @ 2900", "source": "telegram"}
          ]
        }
        ```
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: "Example: Using multiple API calls in parallel, but this increases latency and rate limit usage"
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low (nice to have)
        - Medium (would improve workflow)
        - High (blocking current work)
        - Critical (security/data loss risk)
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of LeviBot does this feature relate to?
      options:
        - API (backend endpoints)
        - Panel (frontend UI)
        - ML/Signals (scoring/classification)
        - Risk Engine
        - Execution (paper/live trading)
        - Observability (metrics/logs)
        - Infrastructure (Docker/CI/CD)
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe a specific scenario where this feature would be useful
      placeholder: |
        Example: As a trader monitoring 50+ Telegram channels, I need to score incoming signals in real-time without hitting rate limits.
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or references
      placeholder: "Screenshots, links to similar features in other tools, etc."
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: This feature aligns with LeviBot's core purpose (signal scoring + risk management)
          required: true
        - label: I am willing to contribute to this feature (optional)
          required: false
