# LSE Production Configuration
# price_source sabitleme + MEXC feed entegrasyonu

symbol: BTCUSDT
mode: paper # paper | real
leverage: 3

# Quote budget per trade
quote_budget: 1000

# Time windows (seconds)
windows: [3, 15, 60]

# ATR configuration
atr:
  period: 14
  k_enter: 0.8

# Z-score configuration
zscore:
  lookback: 120
  z_enter: 1.5

# Risk management
risk:
  max_daily_dd: 0.02
  max_open_trades: 1
  slippage_bps: 1.5
  fee_bps: 7
  hard_stop_bps: 15
  take_profit_bps: 25

# Entry filters
filters:
  min_vol_bps: 5
  max_spread_bps: 1
  max_latency_ms: 120

# Price source (CRITICAL: Use WS for real-time)
price_source: ws_mid # ws_mid | best_bid | best_ask | ca_ohlc
prefer_ws_price: true # Always prefer WS over DB/CA

# Price guards (prevent anomalies)
price_guards:
  enabled: true
  median_check:
    enabled: true
    window_sec: 300 # 5 minutes
    threshold_pct: 10 # ±10%
  clamps:
    min_price: 10000 # $10k minimum for BTC
    max_price: 150000 # $150k maximum for BTC

# Recording
recording:
  parquet: false
  path: data/lse/

