# Swing Engine Configuration
# Multi-day position trading (4H-1D timeframe)

symbol: BTCUSDT
mode: paper
leverage: 1 # Conservative for swing
quote_budget: 2000.0
base_tf: "4h"

# Trend following
ema_fast: 21
ema_slow: 55

# Breakout detection
donchian_period: 20

# Momentum & volatility
rsi_period: 14
atr_period: 14
atr_stop_mult: 2.5

# Trend strength
adx_period: 14
min_adx: 20.0

# Risk management
risk:
  max_daily_dd: 0.05
  max_open_trades: 1
  slippage_bps: 0.5
  fee_bps: 7
  hard_stop_bps: 30
  take_profit_bps: 60
  rr_min: 1.5

# Entry filters
filters:
  min_vol_bps: 15
  max_spread_bps: 2.0
  max_latency_ms: 200

# Data recording
recording:
  parquet: false
  path: "data/swing/"
