version: "3.9"
services:
  minio:
    image: minio/minio:RELEASE.2025-01-11T00-00-00Z
    container_name: levibot-minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web console
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s

  mc:
    image: minio/mc:RELEASE.2025-01-11T00-00-00Z
    container_name: levibot-mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: |
      /bin/sh -c '
      mc alias set local http://minio:9000 "$$MINIO_ROOT_USER" "$$MINIO_ROOT_PASSWORD" && \
      mc mb -p local/${S3_LOG_BUCKET:-levibot-logs} || true && \
      echo "MinIO ready; bucket ensured: $${S3_LOG_BUCKET:-levibot-logs}" && sleep 3600
      '
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
      - S3_LOG_BUCKET=${S3_LOG_BUCKET:-levibot-logs}
volumes:
  minio-data:
