name: Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 3 * * 1"   # her Pazartesi

permissions:
  contents: read
  security-events: write

jobs:
  codeql:
    name: CodeQL (Python & JS)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
        with:
          languages: python, javascript
      - uses: github/codeql-action/autobuild@v3
      - uses: github/codeql-action/analyze@v3
        with:
          category: "/language:python"
      - uses: github/codeql-action/analyze@v3
        with:
          category: "/language:javascript"

  bandit:
    name: Bandit (Python SAST)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install bandit
          bandit -r backend/src -f sarif -o bandit.sarif || true
      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: bandit.sarif
